package templates

var Header = `
// Code generated by Restify. DO NOT EDIT.

// go:generate restify
// +build !restified


package {{.PackageName}}

import (
	"echo/pkg/models"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/gorilla/mux"
	"github.com/pkg/errors"
)

// NewRouter ...
func NewRouter() *mux.Router {
	// Create router
	mux := mux.NewRouter()

	// Register route handlers
	mux.HandleFunc("/contacts", ContactsServiceCreateHandler).Methods("POST")
	mux.HandleFunc("/contacts/{id}", ContactsServiceGetOneHandler).Methods("GET")

	return mux
}

`
