// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"context"
	"github.com/bilal-bhatti/echo/pkg/connectors"
	"net/http"
)

// Injectors from wire.go:

func InitContactsService() (*ContactsService, error) {
	dataConnector := connectors.ProvideDataConnector()
	identityConnector := connectors.ProvideIdentityConnector()
	elasticSearchConnector := connectors.ProvideElasticSearchConnector()
	contactsService := &ContactsService{
		Data:          dataConnector,
		Identity:      identityConnector,
		ElasticSearch: elasticSearchConnector,
	}
	return contactsService, nil
}

func InitThingsService() (*ThingsService, error) {
	dataConnector := connectors.ProvideDataConnector()
	identityConnector := connectors.ProvideIdentityConnector()
	elasticSearchConnector := connectors.ProvideElasticSearchConnector()
	thingsService := &ThingsService{
		Data:          dataConnector,
		Identity:      identityConnector,
		ElasticSearch: elasticSearchConnector,
	}
	return thingsService, nil
}

// wire.go:

func ProvideContext(r *http.Request) context.Context {
	return r.Context()
}
